jobs:
- job: Build
  timeoutInMinutes: 10
  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: self
    submodules: true
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3"

  - bash: |-
      python3 -m pip install --upgrade pip && pip3 install -r requirements.txt
    displayName: Install Requirements

  - task: PipAuthenticate@0
    inputs:
      artifactFeeds: 'pros-cli'

  - script: ./scripts/build.sh
    displayName: 'Build Documentation'

  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: artifacts
      artifactName: pros-docs.tar.gz
    displayName: Upload pros-docs.tar.gz
    condition: succeeded()